
POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Os maiores animais do mundo",
    "description": "Video sobre animais",
    "duration": 600
}

### 

GET http://localhost:3333/videos

###

GET http://localhost:3333/videos?search=animais

### 

PUT http://localhost:3333/videos/67d67e43-7ccc-4623-a10e-b2bb0b0c2343
Content-Type: application/json

{
    "title": "Animais raros e impressionantes",
    "description": "Video sobre animais",
    "duration": 600
}

### 

DELETE http://localhost:3333/videos/36b8f84d-df4e-4d49-b662-bcde71a8764f

